GET  https://convert.loca.lt/download-file?id=fsafssssssssssaas HTTP/1.1

####
POST  https://convert.loca.lt/download 
content-type: application/json

{
    "url": "https://www.youtube.com/watch?v=eV97KXhmaLY&ab_channel=CodingWithChip",
    "deviceID": "fsafssssssssssaas"
}
####
GET http://192.168.0.14:19000/file?id=5dab2f1c19bc7bc1

####
GET http://192.168.0.14:19000/download?id=5dab2f1c19bc7bc1 HTTP/1.1
